version: '3'

services:
  mydb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dj
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /home/proj/scripts/init.sh
    environment:
      DJANGO_USER: root
      DJANGO_PASS: rootroot
      WEBADDRESS: 127.0.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: mydb
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: abc
      PYTHONUNBUFFERED: 1
    volumes:
      - ./:/home/proj/
    ports:
      - "8000:8000"
    depends_on:
      - mydb

