version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /home/proj/scripts/init.sh
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "8000:8000"
