version: '3'

services:
  myweb:
    build: .
    command: python3 /home/proj/manage.py runserver 0.0.0.0:8000
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "8000:8000"
  prom:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - myweb
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    links:
      - prom
    depends_on:
      - prom
